////#include "CAU_TRUC_DU_LIEU.h"
#pragma once
#include "menu.h"

//NOTE: /////////QUAN TRONG: DAT VE NEU KHONG CO CMND THI BAT NHAP THONG TIN TRUOC// KHI VAO DAT VE HOI HK DA CO CMND HAY CHUA//??
//////////// TIM PHUONG AN PHAN BIET HK CHUA CO CMND ////////////////??
//NOTE:  //////////						CUC KY QUAN TRONG	//DONE	OR   NOT?						//////////////////
//							XEM LAI DANH SACH HANH KHACH SAI CHO NAO//DONE			/////	NEN BO CAY NHI PHAN TIM KIEM CAN bnag
//NOTE: HAM HO_TRO_XOA_MB LOI: BAM ESC THI NHAN VE GIA TRI 27 (MB[27]) // DONE
//NOTE: NEU KHONG CO HANH KHACH NAO TREN CHUYEN BAY MA TOI GIO KHOI HANH THI TU DONG HUY CHUYEN BAY /// DONE
//NOTE: HAM HUY VE KHI IN DS CB CHUA TAO TRANG	/// DONE
//NOTE: MAY BAY HIEN TAI || TUONG LAI CO CHUYEN BAY THI KHONG XOA DUOC || XOA THI CAC CHUYEN BAY DO TU DONG HUY   //// DONE
//NOTE: DAT_VE BO STRUCT CUC BO/// DUYET DANH SACH CHUYEN BAY VOI DIEU KIEN CB_TUONG_LAI	///NEN TAO STRUCT CB VI: SOFT THEO SBD, NEN IT CB
//																							TAO STRUCT DE DO TON THOI GIAN DUYET DSLKD (PTR_CB)
//NOTE: DAT_VE NHAP LAI THONG TIN HANH KHACH LOI //// DONE
//NOTE: DATE_VE CACH NHAU 1 GIO LIET KE TAT CA CHUYEN BAY VI PHAM DK  (CHI CO TOI DA 2 CB VI PHAM DK) //DONE
//NOTE: TAO MB SO VE <= 200 ////DONE
//NOTE: CHU Y LENH SYSTEM("PAUSE"); 
//NOTE: NHO SUA LAI CAU TRUC DU LIEU CUA DSHK THANH CAY NHI PHAN TIM KIEM (BO bf = 1; TRONG CTDL) (NHAP LAI DSHK)
//NOTE: HAM XOA_MB KHI XOA 1 MB ROI BAM ESC BI LOI //DONE


int main() {
	menu();
	/*int n = 1000;
	int* a = new int[n];
	for (int i = 0; i < n; a[i] = i, i++);
	char macb[10] = "VN000";
	int so = 1;
	ghi_file_mang_CB(a, n, so, macb);
	delete[] a;*/
	return 0;
}
